### ISSUE TITLE
Alarm support

### ISSUE THREAD

**Issue by polcape** [martindybal/taphome-homeassistant#11]
Using [Alarm panel entity](https://developers.home-assistant.io/docs/core/entity/alarm-control-panel) add support to alarm devices

**Comment by martindybal** [comment]
@polcape virtual Alarm device don't show hint in TapHome cloud api setting. Do you know which values should be used?

**Comment by polcape** [comment]
Yes, my Alarm have this type: 7, 19, 20, 21

**Comment by martindybal** [comment]
This is virtual Alarm `getDeviceValue`. @polcape Can you share your? But I don't know what values means. I'll try to figure it out from TapHome UI

```yaml
{
  "deviceId": 7,
  "values": [
    {
      "valueTypeId": 7,
      "valueTypeName": "DeviceStatus",
      "value": 0
    },
    {
      "valueTypeId": 19,
      "valueTypeName": "AlarmMode",
      "value": 1
    },
    {
      "valueTypeId": 20,
      "valueTypeName": "AlarmState",
      "value": 0
    },
    {
      "valueTypeId": 22,
      "valueTypeName": "OperationMode",
      "value": 0
    },
    {
      "valueTypeId": 23,
      "valueTypeName": "ManualTimeout",
      "value": 0
    }
  ],
  "timestamp": 2108910535584
}
```
