### ISSUE TITLE
Allow multiple TapHome system control

### ISSUE THREAD

**Issue by polcape** [martindybal/taphome-homeassistant#30]
If I want to import in HA some object from one TapHome core A and other object from another TapHome core B I can't now, because only one token it can be managed in the platform.

It would be useful allow multiple token like HA modbus platform (https://www.home-assistant.io/integrations/modbus/) for example in a way like this:

```
taphome:
   - token: safasfdasfsafa
      name: hub1

   - token: fdfsdssfsd
      name: hub2
```

```
taphome:
   - hub: hub1
     lights:
       - 1
       - 2 

   - hub: hub2
     lights:
       - 1
       - 2 
```

**Comment by martindybal** [comment]
That's good point it should be implemented soon. Because it requires breaking change in configuration.

**Comment by martindybal** [comment]
What about this:

```
taphome:
  - core: 1st floor
    token: XXXXXXXX
    lights:
      - 1
      - 2
    covers:
      - 3
      - 4
      - 5
  - core: 2nd floor
    token: XXXXXXXX
    lights:
      - 4
      - 5
    covers:
      - 1
      - 2
      - 3
```

**Comment by polcape** [comment]
I think is better give the possibility to split the configuration, for better management.
So made a statement with core and token declaration, detachment from entity decalaration.

Because a user can split taphome configuration in many file like this:

taphome_init.yaml
`
taphome:
  - core: 1st_floor
    token: XXXXXXXX
  - core: 2nd_floor
    token: XXXXXXXX
`

taphome_light.yaml
`
taphome:
  - core: 2nd_floor
    lights:
      - 4
      - 5
  - core: 1st_floor
    lights:
      - 4
      - 5
`

taphome_covers.yaml
`
taphome:
  - core: 2nd_floor
    covers:
      - 4
      - 5
  - core: 1st_floor
    covers:
      - 4
      - 5
`


Or maybe split the configuration in files one per floor

taphome_1st.yaml
`
taphome:
  - core: 1st_floor
    lights:
      - 4
      - 5
  - core: 1st_floor
    covers:
      - 4
      - 5
`

taphome_2nd.yaml
`
taphome:
  - core: 2nd_floor
    lights:
      - 4
      - 5
  - core: 2nd_floor
    covers:
      - 4
      - 5
`

What do you think about it?=

**Comment by martindybal** [comment]
I don't know if Home Assistant has support for this. Can you prepare demo of configuration? Do you know some integration with these type of config?

**Comment by polcape** [comment]
Hello @martindybal, the only integration that I know working like that is modbus one (https://www.home-assistant.io/integrations/modbus/)

**Comment by martindybal** [comment]
I prepared simplest way how to do it https://github.com/martindybal/taphome-homeassistant/tree/feature/allow-multiple-core-units. We can add options for more config files later

```yaml
taphome:
  - token: 00000000-0000-0000-0000-000000000000
    lights:
      - 1
      - 2
  - token: 00000000-0000-0000-0000-000000000000
    lights:
      - 1
    covers:
      - 6
```

But there is no space for global TapHome integration config. It might come be handy in the future.

My suggestion: 
```yaml
taphome:
  some-future-global-config: true
  cores:
    - token: 00000000-0000-0000-0000-000000000000
      lights:
        - 1
        - 2
      covers:
        - 3
        - 4
        - 5
    - token: 00000000-0000-0000-0000-000000000000
      lights:
        - 1
      covers:
        - 6
```
